// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yezvkzscytyfazudfklf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InllenZrenNjeXR5ZmF6dWRma2xmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk5MDcwOTIsImV4cCI6MjA3NTQ4MzA5Mn0.7G5faBunRUuXyR_hVddCp6i1xpAh0NRdH3SUZer-6LY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});